export default {
    buildPrompt: (jobData) => {
        return `You are a professional service technician writing a detailed service report.

Job Information:
- Job Number: ${jobData.job_number || 'N/A'}
- Category: ${jobData.category || 'N/A'}
- Date: ${jobData.scheduled_date || new Date().toISOString().split('T')[0]}

Customer & Asset:
- Customer: ${jobData.customer?.name || 'N/A'}
- Location: ${jobData.customer?.location || 'N/A'}
- Vehicle Type: ${jobData.asset?.type || 'N/A'}
- Serial Number: ${jobData.asset?.serial_number || 'N/A'}
- Fleet Number: ${jobData.asset?.fleet_number || 'N/A'}

Technician: ${jobData.technician?.name || 'N/A'}

Work Performed:
${jobData.work_performed?.map((work, i) => `${i + 1}. ${work}`).join('\n') || 'No work details provided'}

Parts Used:
${jobData.parts_used?.map(part => `- ${part.name} (${part.part_number}) - Qty: ${part.quantity}`).join('\n') || 'No parts used'}

Notes: ${jobData.notes || 'No additional notes'}

Generate a professional service report with the following sections:

1. **IMMEDIATE REPLACEMENTS REQUIRED**: List any parts or components that MUST be replaced immediately due to safety concerns or failure. If none, write "None identified during this service."

2. **COMPONENTS IN GOOD CONDITION**: List all parts and systems that were inspected and found to be in good working order.

3. **PREVENTIVE MAINTENANCE RECOMMENDATIONS**: Suggest parts or services that should be addressed in the next 1-3 months to prevent future issues.

4. **SERVICE SUMMARY**: Provide a brief 2-3 sentence summary of the overall vehicle condition and work completed.

Write in a clear, professional tone. Be specific about part names and conditions. Format the report with clear headers and bullet points.`;
    },

    format: (aiResponse, jobData) => {
        return {
            title: `${jobData.category} Report - ${jobData.job_number}`,
            content: `# ${jobData.category} Report

**Job Number:** ${jobData.job_number || 'N/A'}  
**Date:** ${jobData.scheduled_date || new Date().toLocaleDateString()}  
**Status:** ${jobData.status || 'Completed'}

---

## Customer Information
- **Name:** ${jobData.customer?.name || 'N/A'}
- **Location:** ${jobData.customer?.location || 'N/A'}
- **Contact:** ${jobData.customer?.contact || 'N/A'}

## Asset Details
- **Type:** ${jobData.asset?.type || 'N/A'}
- **Serial Number:** ${jobData.asset?.serial_number || 'N/A'}
- **Fleet Number:** ${jobData.asset?.fleet_number || 'N/A'}
- **Odometer:** ${jobData.odometer_reading || 'N/A'}

## Technician
**${jobData.technician?.name || 'N/A'}** (${jobData.technician?.id || 'N/A'})

---

${aiResponse}

---

*Report Generated: ${new Date().toLocaleString()}*
*Generated by: Zuper AI Report System*`,
            metadata: {
                job_id: jobData.job_uid,
                job_number: jobData.job_number,
                category: jobData.category,
                generated_at: new Date().toISOString()
            }
        };
    }
};
